// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

export type EndpointInfo = { fullname: string, id: string, name: string | null, ip: string | null, port: string | null, rtype: DeviceType | null, present: boolean | null, 
/**
 * Set when this peer was found by scanning our QR code. Scanning is itself
 * the user choosing us, so the sender connects without further prompting.
 */
qr_match: boolean | null, };
